# fly.toml app configuration file generated for weather-clock-dashboard-vc on 2026-05-09T08:00:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-clock-dashboard-vc'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
